SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [AutocareHCB].[dbo].[DiseasePerBloodCodes](
	[index] [tinyint] NOT NULL,
	[disease] [nvarchar](50) NULL,
	[analysis_index] [nvarchar](50) NULL
) ON [PRIMARY]
GO
ALTER TABLE [AutocareHCB].[dbo].[DiseasePerBloodCodes] ADD  CONSTRAINT [PK_BloodCodePerDisease] PRIMARY KEY CLUSTERED 
(
	[index] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
